CREATE TABLE IF NOT EXISTS product(
  productId INT NOT NULL AUTO_INCREMENT
  ,productName VARCHAR(255) DEFAULT NULL
  ,unitPrice INT DEFAULT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY(productId)
);